# Generated by Django 2.1.3 on 2018-11-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181126_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='instance_id',
            new_name='instance',
        ),
    ]
